name: VoidBounty
main: org.ayosynk.voidBounty.VoidBounty
version: 1.0
api-version: 1.21.1
author: AyoSynk
description: >
  A bounty plugin where players earn bounties by killing players or mobs, with customizable features, mob blacklist, streak multipliers, and more.

commands:
  bounty:
    description: >
      Main command for managing bounties, including setting, removing, viewing,
      displaying leaderboards, and adding new roles.
    usage: /bounty <set|remove|player_name|leaderboard> [arguments]
    aliases: [bounty, bounties, b]
    permission: voidbounty.command.bounty

# Permissions Configuration
permissions:
  # General Bounty Command Permission
  voidbounty.command.bounty:
    description: Allows the player to use the /bounty command and its subcommands.
    default: true

  # Admin Permission for Managing Bounties and Roles
  voidbounty.admin:
    description: Allows access to admin-specific bounty commands such as addrole.
    default: op

# Dependencies
depend:
  - Vault  # Required for economy integration

softdepend:
  - EssentialsX  # Optional: Enhances economy compatibility and provides additional utilities
  - Geyser        # Optional: Enables cross-play compatibility between Java and Bedrock editions
